language: java
jdk:
  - oraclejdk11
  - openjdk11

services:
  - docker

branches:
  only:
    - master
    - develop

script:
  - ./mvnw -PIT verify -B

after_success:
  - bash <(curl -s https://codecov.io/bash)